# Conversation metadata
conversation:
  name: "Healthcare Prior Authorization"
  version: "2.1.1"
  client_id: "prior_auth"

# Global behavioral constraints
guardrails:
  language:
    allowed: ["en", "en-US"]
    enforcement: "strict"
    fallback_message: "I apologize, but I can only communicate in English for this verification call."
  
  tone:
    style: "professional_medical"
    stability: "high"
    mirroring_prevention: true
    guidelines:
      - "Maintain professional medical office assistant tone at all times"
      - "Do not mirror or adopt the caller's speaking style, accent, or informal language"
      - "Remain calm and courteous regardless of caller's tone or behavior"
      - "Use complete sentences and proper grammar"
  
  data_integrity:
    source: "database_only"
    hallucination_prevention: true
    guidelines:
      - "Only provide patient information that is explicitly present in the PATIENT INFORMATION section"
      - "Never guess, estimate, or fabricate any patient details"
      - "If information is not provided, say 'I don't have that information available' rather than making it up"
  
  topic_constraints:
    allowed_topics:
      - "insurance verification"
      - "patient eligibility"
      - "prior authorization"
      - "benefit verification"
    prohibited_topics:
      - "personal conversations"
      - "medical advice"
      - "billing disputes"
      - "unrelated small talk"
    off_topic_response: "I apologize, but I'm only able to assist with insurance verification for this patient today. Let's continue with the authorization details."

# Voice configuration
voice:
  persona:
    name: "Alexandra"
    role: "Medical office assistant"
    company: "Adam's Medical Practice"
  
  speaking_style:
    tone: "professional, friendly"
    pace: "moderate"
    max_words_per_response: 30
    consistency: "strict" 

# Data schema - ALL fields available in ALL states
data_schema:
  entity_name: "Patient"
  
  required_fields:
    - patient_id
    - patient_name
    - date_of_birth
    - facility
    - insurance_company
    - insurance_member_id
    - insurance_phone
    - cpt_code
    - provider_npi
    - provider_name
    - appointment_time
  
  global_access: true  # All fields accessible from any state
  
  preformat_rules:
    date_of_birth:
      format: "natural_speech"
      example: "March 15th, 1985"
    
    insurance_member_id:
      format: "spell_out"
      example: "A-S-D-4-8-9-R-T-Y-B-B-B"
    
    cpt_code:
      format: "individual_digits"
      example: "9-9-2-1-3"
    
    provider_npi:
      format: "grouped_digits"
      grouping: [3, 3, 4]
      example: "157-894-3251-6478"
    
    appointment_time:
      format: "natural_speech"
      example: "October 22nd, 2025 at 3:30 PM"

# State machine
states:
  initial_state: "connection"
  
  definitions:
    # Event-driven states - DO NOT MODIFY BEHAVIOR
    - name: "connection"
      description: "Call connected - waiting for other party to speak first"
      prompts_ref: "connection"
      entry_point: true
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time
    
    - name: "voicemail_detected"
      description: "Voicemail system detected - leave message and end call"
      prompts_ref: "voicemail_detected"
      terminal: true
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time
    
    - name: "ivr_navigation"
      description: "Navigating IVR system to reach human representative"
      prompts_ref: "ivr_navigation"
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time
    
    - name: "ivr_stuck"
      description: "IVR navigation failed - unable to reach human"
      prompts_ref: "ivr_stuck"
      terminal: true
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time
    
    # Conversation states - ENABLE LLM DIRECTION
    - name: "greeting"
      description: "Initial greeting after reaching human representative"
      prompts_ref: "greeting"
      allowed_transitions: ["patient_verification"]
      llm_directed: false  # Keep keyword-based transition
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time
    
    - name: "verification"
      description: "Provide patient information and verify insurance coverage"
      prompts_ref: "verification"
      data_access:
        - patient_name
        - date_of_birth
        - insurance_member_id
        - cpt_code
        - provider_npi
        - patient_id
        - provider_name
        - facility
        - insurance_company
        - appointment_time
      functions:
        - update_prior_auth_status
      allowed_transitions: ["closing", "greeting"]
      llm_directed: true
      required_before_closing: true
    
    - name: "closing"
      description: "Close the call politely"
      prompts_ref: "closing"
      terminal: true
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time

# Transition rules
transitions:
  # ============================================================================
  # EVENT-DRIVEN TRANSITIONS (IVR/Voicemail/Human Classification)
  # ============================================================================
  
  # Transition 1: connection → voicemail_detected (via event handler)
  - from_state: "connection"
    to_state: "voicemail_detected"
    trigger:
      type: "event"
      event_name: "on_voicemail_detected"
    reason: "voicemail_system_detected"
    description: "VoicemailDetector classified call as voicemail system"
  
  # Transition 2: connection → ivr_navigation (via event handler)
  - from_state: "connection"
    to_state: "ivr_navigation"
    trigger:
      type: "event"
      event_name: "on_ivr_status_changed:DETECTED"
    reason: "ivr_system_detected"
    description: "IVRNavigator detected IVR system requiring navigation"
  
  # Transition 3: connection → greeting (via event handler - human answered)
  - from_state: "connection"
    to_state: "greeting"
    trigger:
      type: "event"
      event_name: "on_conversation_detected"
    reason: "human_answered_directly"
    description: "Human answered call directly (no IVR system)"
  
  # Transition 4: ivr_navigation → greeting (via event handler - IVR complete)
  - from_state: "ivr_navigation"
    to_state: "greeting"
    trigger:
      type: "event"
      event_name: "on_ivr_status_changed:COMPLETED"
    reason: "ivr_navigation_complete"
    description: "Successfully navigated IVR to reach human"
  
  # Transition 5: ivr_navigation → ivr_stuck (via event handler - IVR stuck)
  - from_state: "ivr_navigation"
    to_state: "ivr_stuck"
    trigger:
      type: "event"
      event_name: "on_ivr_status_changed:STUCK"
    reason: "ivr_navigation_failed"
    description: "IVR navigation failed - unable to proceed"
  
  # ============================================================================
  # AUTO TRANSITION
  # ============================================================================
  
  # Transition 6: greeting → verification
  - from_state: "greeting"
    to_state: "verification"
    trigger:
      type: "auto"  # Triggers on ANY user response
      delay: 0
    reason: "greeting delivered"
    description: "Greeting delivered - ready for verification conversation"