# Conversation metadata
conversation:
  name: "Healthcare Prior Authorization"
  version: "2.1.1"
  client_id: "prior_auth"

# Global behavioral constraints
guardrails:
  language:
    allowed: ["en", "en-US"]
    enforcement: "strict"
    fallback_message: "I apologize, but I can only communicate in English for this verification call."
  
  tone:
    style: "professional_medical"
    stability: "high"
    mirroring_prevention: true
    guidelines:
      - "Maintain professional medical office assistant tone at all times"
      - "Do not mirror or adopt the caller's speaking style, accent, or informal language"
      - "Remain calm and courteous regardless of caller's tone or behavior"
      - "Use complete sentences and proper grammar"
  
  data_integrity:
    source: "database_only"
    hallucination_prevention: true
    guidelines:
      - "Only provide patient information that is explicitly present in the PATIENT INFORMATION section"
      - "Never guess, estimate, or fabricate any patient details"
      - "If information is not provided, say 'I don't have that information available' rather than making it up"
  
  topic_constraints:
    allowed_topics:
      - "insurance verification"
      - "patient eligibility"
      - "prior authorization"
      - "benefit verification"
    prohibited_topics:
      - "personal conversations"
      - "medical advice"
      - "billing disputes"
      - "unrelated small talk"
    off_topic_response: "I apologize, but I'm only able to assist with insurance verification for this patient today. Let's continue with the authorization details."

# Voice configuration
voice:
  persona:
    name: "Alexandra"
    role: "Medical office assistant"
    company: "Adam's Medical Practice"
  
  speaking_style:
    tone: "professional, friendly"
    pace: "moderate"
    max_words_per_response: 30
    consistency: "strict" 

# Data schema - ALL fields available in ALL states
data_schema:
  entity_name: "Patient"
  
  required_fields:
    - patient_id
    - patient_name
    - date_of_birth
    - facility
    - insurance_company
    - insurance_member_id
    - insurance_phone
    - cpt_code
    - provider_npi
    - provider_name
    - appointment_time
  
  global_access: true

# State machine
states:
  initial_state: "call_classifier"

  definitions:
    - name: "call_classifier"
      description: "Classify if call is answered by IVR system or human"
      prompts_ref: "call_classifier"
      allowed_transitions: ["ivr_navigation", "greeting"]
      llm_directed: false
      data_access: []

    - name: "ivr_navigation"
      description: "Navigating IVR system to reach human representative"
      prompts_ref: "ivr_navigation"
      allowed_transitions: []
      llm_directed: false
      data_access: []
    
    - name: "ivr_stuck"
      description: "IVR navigation failed - unable to reach human"
      prompts_ref: "ivr_stuck"
      terminal: true
      allowed_transitions: []
      llm_directed: false
      data_access: []
    
    - name: "greeting"
      description: "Greet the human representative briefly"
      prompts_ref: "greeting"
      data_access:
        - patient_name
        - cpt_code
        - facility
      allowed_transitions: ["verification"]
      llm_directed: true

    - name: "verification"
      description: "Provide patient information and verify insurance coverage"
      prompts_ref: "verification"
      data_access:
        - patient_name
        - date_of_birth
        - insurance_member_id
        - cpt_code
        - provider_npi
        - patient_id
        - provider_name
        - facility
        - insurance_company
        - appointment_time
      functions:
        - update_prior_auth_status
      allowed_transitions: ["supervisor_confirmation", "closing"]
      llm_directed: true
      required_before_closing: true

    - name: "supervisor_confirmation"
      description: "Confirm if caller wants to speak with supervisor"
      prompts_ref: "supervisor_confirmation"
      data_access:
        - patient_id
      functions:
        - dial_supervisor
      allowed_transitions: ["verification"]
      llm_directed: true

    - name: "closing"
      description: "Close the call politely"
      prompts_ref: "closing"
      terminal: true
      allowed_transitions: []
      llm_directed: false
      data_access:
        - patient_id
        - patient_name
        - date_of_birth
        - facility
        - insurance_company
        - insurance_member_id
        - insurance_phone
        - cpt_code
        - provider_npi
        - provider_name
        - appointment_time

# Transition rules
transitions:
  # ============================================================================
  # EVENT-DRIVEN TRANSITIONS (IVR/Human Classification)
  # ============================================================================
  # Note: IVRNavigator handles initial classification and event handlers transition directly to
  # verification (human) or ivr_navigation (IVR system). Hardcoded greeting sent in handlers.

  # Transition 1: ivr_navigation → verification (via event handler - IVR complete)
  - from_state: "ivr_navigation"
    to_state: "verification"
    trigger:
      type: "event"
      event_name: "on_ivr_status_changed:COMPLETED"
    reason: "ivr_navigation_complete"
    description: "Successfully navigated IVR to reach human, transition to verification"

  - from_state: "ivr_navigation"
    to_state: "ivr_stuck"
    trigger:
      type: "event"
      event_name: "on_ivr_status_changed:STUCK"
    reason: "ivr_navigation_failed"
    description: "IVR navigation failed - unable to proceed"