
# Conversation metadata
conversation:
  name: "Healthcare Prior Authorization"
  version: "2.0.0"
  client_id: "prior_auth"

# Voice configuration
voice:
  persona:
    name: "Alexandra"
    role: "Medical office assistant"
    company: "Adam's Medical Practice"
  
  speaking_style:
    tone: "professional, friendly"
    pace: "moderate"
    max_words_per_response: 30

# Data schema
data_schema:
  entity_name: "Patient"
  
  required_fields:
    - patient_name
    - date_of_birth
    - insurance_member_id
    - cpt_code
    - provider_npi
  
  preformat_rules:
    date_of_birth:
      format: "natural_speech"
    
    insurance_member_id:
      format: "spell_out"
    
    cpt_code:
      format: "individual_digits"
    
    provider_npi:
      format: "grouped_digits"
      grouping: [3, 3, 4]

# State machine
states:
  initial_state: "greeting"
  
  definitions:
    - name: "greeting"
      description: "Initial greeting after insurance rep answers"
      prompts_ref: "greeting"
    
    - name: "patient_verification"
      description: "Provide patient information when requested"
      prompts_ref: "patient_verification"
      data_access:
        - patient_name
        - date_of_birth
        - insurance_member_id
        - cpt_code
        - provider_npi

# Transition rules - Configure conversation flow here without touching Python!
transitions:
  # Transition 1: greeting → patient_verification
  - from_state: "greeting"
    to_state: "patient_verification"
    trigger:
      type: "keyword_detection"
      keywords:
        - "patient"
        - "name"
        - "member"
        - "birthday"
        - "dob"
        - "date of birth"
        - "id"
        - "social"
        - "policy"
        - "subscriber"
        - "information"
        - "verify"
        - "eligibility"
        - "benefits"
      match_mode: "any"
    reason: "rep_asked_for_patient_info"
    description: "Insurance rep is asking for patient information"